acm:
  data-id: kafka.monitor.info.set
  group: GLOBAL_SIJIBAO_BASIC_GROUP
  acmConfigPath: acmConfig.properties
  nacosLocalSnapshotPath: /wyyt/etc/acm/kafka-monitor
  nacosLogPath: /wyyt/logs/kafka-monitor

server:
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  servlet:
    session:
      timeout: 180m
      tracking-modes: cookie
      cookie:
        http-only: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: kafka-monitor
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  aop:
    proxy-target-class: true
  jmx:
    default-domain: ${spring.application.name}
  freemarker:
    allow-session-override: true
    check-template-location: true
    suffix: .ftl
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    settings:
      auto_import: common/spring.ftl as spring
      number_format: '0.##'

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl